import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from './providers';
import Navigation from "./components/navigation/Navigation";
import Header from "./components/Header/Header";
import HeaderWrapper from "./components/headerWrapper";

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins`}>
        <HeaderWrapper />
        {/* <Navigation /> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
