import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import HeaderWrapper from './components/headerWrapper';
import { Toaster } from 'sonner';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Tarabezah',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
      </head>
      <body className={`${poppins.variable} font-poppins`}>
        <HeaderWrapper />
        {/* <Navigation /> */}
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
